# Generated by Django 4.1.1 on 2022-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.ManyToManyField(blank=True, to='restaurant.ingredient'),
        ),
    ]
