# Generated by Django 4.1.1 on 2022-09-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.TextField()),
                ('ingredient', models.ManyToManyField(to='restaurant.ingredient')),
            ],
        ),
    ]
